<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Bharath" failures="1" tests="10" name="Test" time="2.089" errors="0" timestamp="2025-10-03T22:18:43 IST">
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase1" time="0.01"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase1" time="0.001"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase1" time="0.001"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase5" time="0.003">
    <skipped/>
  </testcase> <!-- testCase5 -->
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase5" time="0.001">
    <skipped/>
  </testcase> <!-- testCase5 -->
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase5" time="0.001">
    <failure type="java.lang.AssertionError" message="Failing test case 5 due to  &amp;lt;&amp;lt; Data Issue &amp;gt;&amp;gt;">
      <![CDATA[java.lang.AssertionError: Failing test case 5 due to  << Data Issue >>
at testng.framework.concepts.AppCommons.testCase5(AppCommons.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testCase5 -->
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase4" time="2.007"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="loginTest" time="0.006"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="loginTest" time="0.0"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="loginTest" time="0.001"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test -->
